package glyphs

// Font5x7 is a complete 5×7 pixel monospace font
// Extracted and expanded from internal/widget/error.go
var Font5x7 = &GlyphSet{
	Name:        "5x7",
	GlyphWidth:  5,
	GlyphHeight: 7,
	Glyphs: map[rune]*Glyph{
		// Uppercase letters A-Z
		'A': {
			Width: 5, Height: 7,
			Data: [][]bool{
				{false, true, true, true, false},
				{true, false, false, false, true},
				{true, false, false, false, true},
				{true, true, true, true, true},
				{true, false, false, false, true},
				{true, false, false, false, true},
				{true, false, false, false, true},
			},
		},
		'B': {
			Width: 5, Height: 7,
			Data: [][]bool{
				{true, true, true, true, false},
				{true, false, false, false, true},
				{true, false, false, false, true},
				{true, true, true, true, false},
				{true, false, false, false, true},
				{true, false, false, false, true},
				{true, true, true, true, false},
			},
		},
		'C': {
			Width: 5, Height: 7,
			Data: [][]bool{
				{false, true, true, true, false},
				{true, false, false, false, true},
				{true, false, false, false, false},
				{true, false, false, false, false},
				{true, false, false, false, false},
				{true, false, false, false, true},
				{false, true, true, true, false},
			},
		},
		'D': {
			Width: 5, Height: 7,
			Data: [][]bool{
				{true, true, true, true, false},
				{true, false, false, false, true},
				{true, false, false, false, true},
				{true, false, false, false, true},
				{true, false, false, false, true},
				{true, false, false, false, true},
				{true, true, true, true, false},
			},
		},
		'E': {
			Width: 5, Height: 7,
			Data: [][]bool{
				{true, true, true, true, true},
				{true, false, false, false, false},
				{true, false, false, false, false},
				{true, true, true, true, false},
				{true, false, false, false, false},
				{true, false, false, false, false},
				{true, true, true, true, true},
			},
		},
		'F': {
			Width: 5, Height: 7,
			Data: [][]bool{
				{true, true, true, true, true},
				{true, false, false, false, false},
				{true, false, false, false, false},
				{true, true, true, true, false},
				{true, false, false, false, false},
				{true, false, false, false, false},
				{true, false, false, false, false},
			},
		},
		'G': {
			Width: 5, Height: 7,
			Data: [][]bool{
				{false, true, true, true, false},
				{true, false, false, false, true},
				{true, false, false, false, false},
				{true, false, true, true, true},
				{true, false, false, false, true},
				{true, false, false, false, true},
				{false, true, true, true, true},
			},
		},
		'H': {
			Width: 5, Height: 7,
			Data: [][]bool{
				{true, false, false, false, true},
				{true, false, false, false, true},
				{true, false, false, false, true},
				{true, true, true, true, true},
				{true, false, false, false, true},
				{true, false, false, false, true},
				{true, false, false, false, true},
			},
		},
		'I': {
			Width: 5, Height: 7,
			Data: [][]bool{
				{false, true, true, true, false},
				{false, false, true, false, false},
				{false, false, true, false, false},
				{false, false, true, false, false},
				{false, false, true, false, false},
				{false, false, true, false, false},
				{false, true, true, true, false},
			},
		},
		'J': {
			Width: 5, Height: 7,
			Data: [][]bool{
				{false, false, false, false, true},
				{false, false, false, false, true},
				{false, false, false, false, true},
				{false, false, false, false, true},
				{false, false, false, false, true},
				{true, false, false, false, true},
				{false, true, true, true, false},
			},
		},
		'K': {
			Width: 5, Height: 7,
			Data: [][]bool{
				{true, false, false, false, true},
				{true, false, false, true, false},
				{true, false, true, false, false},
				{true, true, false, false, false},
				{true, false, true, false, false},
				{true, false, false, true, false},
				{true, false, false, false, true},
			},
		},
		'L': {
			Width: 5, Height: 7,
			Data: [][]bool{
				{true, false, false, false, false},
				{true, false, false, false, false},
				{true, false, false, false, false},
				{true, false, false, false, false},
				{true, false, false, false, false},
				{true, false, false, false, false},
				{true, true, true, true, true},
			},
		},
		'M': {
			Width: 5, Height: 7,
			Data: [][]bool{
				{true, false, false, false, true},
				{true, true, false, true, true},
				{true, false, true, false, true},
				{true, false, false, false, true},
				{true, false, false, false, true},
				{true, false, false, false, true},
				{true, false, false, false, true},
			},
		},
		'N': {
			Width: 5, Height: 7,
			Data: [][]bool{
				{true, false, false, false, true},
				{true, true, false, false, true},
				{true, false, true, false, true},
				{true, false, false, true, true},
				{true, false, false, false, true},
				{true, false, false, false, true},
				{true, false, false, false, true},
			},
		},
		'O': {
			Width: 5, Height: 7,
			Data: [][]bool{
				{false, true, true, true, false},
				{true, false, false, false, true},
				{true, false, false, false, true},
				{true, false, false, false, true},
				{true, false, false, false, true},
				{true, false, false, false, true},
				{false, true, true, true, false},
			},
		},
		'P': {
			Width: 5, Height: 7,
			Data: [][]bool{
				{true, true, true, true, false},
				{true, false, false, false, true},
				{true, false, false, false, true},
				{true, true, true, true, false},
				{true, false, false, false, false},
				{true, false, false, false, false},
				{true, false, false, false, false},
			},
		},
		'Q': {
			Width: 5, Height: 7,
			Data: [][]bool{
				{false, true, true, true, false},
				{true, false, false, false, true},
				{true, false, false, false, true},
				{true, false, false, false, true},
				{true, false, true, false, true},
				{true, false, false, true, false},
				{false, true, true, false, true},
			},
		},
		'R': {
			Width: 5, Height: 7,
			Data: [][]bool{
				{true, true, true, true, false},
				{true, false, false, false, true},
				{true, false, false, false, true},
				{true, true, true, true, false},
				{true, false, true, false, false},
				{true, false, false, true, false},
				{true, false, false, false, true},
			},
		},
		'S': {
			Width: 5, Height: 7,
			Data: [][]bool{
				{false, true, true, true, false},
				{true, false, false, false, true},
				{true, false, false, false, false},
				{false, true, true, true, false},
				{false, false, false, false, true},
				{true, false, false, false, true},
				{false, true, true, true, false},
			},
		},
		'T': {
			Width: 5, Height: 7,
			Data: [][]bool{
				{true, true, true, true, true},
				{false, false, true, false, false},
				{false, false, true, false, false},
				{false, false, true, false, false},
				{false, false, true, false, false},
				{false, false, true, false, false},
				{false, false, true, false, false},
			},
		},
		'U': {
			Width: 5, Height: 7,
			Data: [][]bool{
				{true, false, false, false, true},
				{true, false, false, false, true},
				{true, false, false, false, true},
				{true, false, false, false, true},
				{true, false, false, false, true},
				{true, false, false, false, true},
				{false, true, true, true, false},
			},
		},
		'V': {
			Width: 5, Height: 7,
			Data: [][]bool{
				{true, false, false, false, true},
				{true, false, false, false, true},
				{true, false, false, false, true},
				{true, false, false, false, true},
				{false, true, false, true, false},
				{false, true, false, true, false},
				{false, false, true, false, false},
			},
		},
		'W': {
			Width: 5, Height: 7,
			Data: [][]bool{
				{true, false, false, false, true},
				{true, false, false, false, true},
				{true, false, false, false, true},
				{true, false, true, false, true},
				{true, false, true, false, true},
				{true, true, false, true, true},
				{true, false, false, false, true},
			},
		},
		'X': {
			Width: 5, Height: 7,
			Data: [][]bool{
				{true, false, false, false, true},
				{true, false, false, false, true},
				{false, true, false, true, false},
				{false, false, true, false, false},
				{false, true, false, true, false},
				{true, false, false, false, true},
				{true, false, false, false, true},
			},
		},
		'Y': {
			Width: 5, Height: 7,
			Data: [][]bool{
				{true, false, false, false, true},
				{true, false, false, false, true},
				{false, true, false, true, false},
				{false, false, true, false, false},
				{false, false, true, false, false},
				{false, false, true, false, false},
				{false, false, true, false, false},
			},
		},
		'Z': {
			Width: 5, Height: 7,
			Data: [][]bool{
				{true, true, true, true, true},
				{false, false, false, false, true},
				{false, false, false, true, false},
				{false, false, true, false, false},
				{false, true, false, false, false},
				{true, false, false, false, false},
				{true, true, true, true, true},
			},
		},

		// Digits 0-9
		'0': {
			Width: 5, Height: 7,
			Data: [][]bool{
				{false, true, true, true, false},
				{true, false, false, false, true},
				{true, false, false, true, true},
				{true, false, true, false, true},
				{true, true, false, false, true},
				{true, false, false, false, true},
				{false, true, true, true, false},
			},
		},
		'1': {
			Width: 5, Height: 7,
			Data: [][]bool{
				{false, false, true, false, false},
				{false, true, true, false, false},
				{false, false, true, false, false},
				{false, false, true, false, false},
				{false, false, true, false, false},
				{false, false, true, false, false},
				{false, true, true, true, false},
			},
		},
		'2': {
			Width: 5, Height: 7,
			Data: [][]bool{
				{false, true, true, true, false},
				{true, false, false, false, true},
				{false, false, false, false, true},
				{false, false, false, true, false},
				{false, false, true, false, false},
				{false, true, false, false, false},
				{true, true, true, true, true},
			},
		},
		'3': {
			Width: 5, Height: 7,
			Data: [][]bool{
				{false, true, true, true, false},
				{true, false, false, false, true},
				{false, false, false, false, true},
				{false, false, true, true, false},
				{false, false, false, false, true},
				{true, false, false, false, true},
				{false, true, true, true, false},
			},
		},
		'4': {
			Width: 5, Height: 7,
			Data: [][]bool{
				{false, false, false, true, false},
				{false, false, true, true, false},
				{false, true, false, true, false},
				{true, false, false, true, false},
				{true, true, true, true, true},
				{false, false, false, true, false},
				{false, false, false, true, false},
			},
		},
		'5': {
			Width: 5, Height: 7,
			Data: [][]bool{
				{true, true, true, true, true},
				{true, false, false, false, false},
				{true, true, true, true, false},
				{false, false, false, false, true},
				{false, false, false, false, true},
				{true, false, false, false, true},
				{false, true, true, true, false},
			},
		},
		'6': {
			Width: 5, Height: 7,
			Data: [][]bool{
				{false, false, true, true, false},
				{false, true, false, false, false},
				{true, false, false, false, false},
				{true, true, true, true, false},
				{true, false, false, false, true},
				{true, false, false, false, true},
				{false, true, true, true, false},
			},
		},
		'7': {
			Width: 5, Height: 7,
			Data: [][]bool{
				{true, true, true, true, true},
				{false, false, false, false, true},
				{false, false, false, true, false},
				{false, false, true, false, false},
				{false, true, false, false, false},
				{false, true, false, false, false},
				{false, true, false, false, false},
			},
		},
		'8': {
			Width: 5, Height: 7,
			Data: [][]bool{
				{false, true, true, true, false},
				{true, false, false, false, true},
				{true, false, false, false, true},
				{false, true, true, true, false},
				{true, false, false, false, true},
				{true, false, false, false, true},
				{false, true, true, true, false},
			},
		},
		'9': {
			Width: 5, Height: 7,
			Data: [][]bool{
				{false, true, true, true, false},
				{true, false, false, false, true},
				{true, false, false, false, true},
				{false, true, true, true, true},
				{false, false, false, false, true},
				{false, false, false, true, false},
				{false, true, true, false, false},
			},
		},

		// Basic punctuation and symbols
		' ': {
			Width: 5, Height: 7,
			Data: [][]bool{
				{false, false, false, false, false},
				{false, false, false, false, false},
				{false, false, false, false, false},
				{false, false, false, false, false},
				{false, false, false, false, false},
				{false, false, false, false, false},
				{false, false, false, false, false},
			},
		},
		'!': {
			Width: 5, Height: 7,
			Data: [][]bool{
				{false, false, true, false, false},
				{false, false, true, false, false},
				{false, false, true, false, false},
				{false, false, true, false, false},
				{false, false, true, false, false},
				{false, false, false, false, false},
				{false, false, true, false, false},
			},
		},
		'.': {
			Width: 5, Height: 7,
			Data: [][]bool{
				{false, false, false, false, false},
				{false, false, false, false, false},
				{false, false, false, false, false},
				{false, false, false, false, false},
				{false, false, false, false, false},
				{false, false, false, false, false},
				{false, false, true, false, false},
			},
		},
		',': {
			Width: 5, Height: 7,
			Data: [][]bool{
				{false, false, false, false, false},
				{false, false, false, false, false},
				{false, false, false, false, false},
				{false, false, false, false, false},
				{false, false, false, false, false},
				{false, false, true, false, false},
				{false, true, false, false, false},
			},
		},
		':': {
			Width: 5, Height: 7,
			Data: [][]bool{
				{false, false, false, false, false},
				{false, false, false, false, false},
				{false, false, true, false, false},
				{false, false, false, false, false},
				{false, false, false, false, false},
				{false, false, true, false, false},
				{false, false, false, false, false},
			},
		},
		';': {
			Width: 5, Height: 7,
			Data: [][]bool{
				{false, false, false, false, false},
				{false, false, false, false, false},
				{false, false, true, false, false},
				{false, false, false, false, false},
				{false, false, false, false, false},
				{false, false, true, false, false},
				{false, true, false, false, false},
			},
		},
		'?': {
			Width: 5, Height: 7,
			Data: [][]bool{
				{false, true, true, true, false},
				{true, false, false, false, true},
				{false, false, false, false, true},
				{false, false, false, true, false},
				{false, false, true, false, false},
				{false, false, false, false, false},
				{false, false, true, false, false},
			},
		},
		'-': {
			Width: 5, Height: 7,
			Data: [][]bool{
				{false, false, false, false, false},
				{false, false, false, false, false},
				{false, false, false, false, false},
				{true, true, true, true, true},
				{false, false, false, false, false},
				{false, false, false, false, false},
				{false, false, false, false, false},
			},
		},
		'/': {
			Width: 5, Height: 7,
			Data: [][]bool{
				{false, false, false, false, true},
				{false, false, false, true, false},
				{false, false, false, true, false},
				{false, false, true, false, false},
				{false, true, false, false, false},
				{false, true, false, false, false},
				{true, false, false, false, false},
			},
		},
		'(': {
			Width: 5, Height: 7,
			Data: [][]bool{
				{false, false, true, false, false},
				{false, true, false, false, false},
				{false, true, false, false, false},
				{false, true, false, false, false},
				{false, true, false, false, false},
				{false, true, false, false, false},
				{false, false, true, false, false},
			},
		},
		')': {
			Width: 5, Height: 7,
			Data: [][]bool{
				{false, false, true, false, false},
				{false, false, false, true, false},
				{false, false, false, true, false},
				{false, false, false, true, false},
				{false, false, false, true, false},
				{false, false, false, true, false},
				{false, false, true, false, false},
			},
		},
		'%': {
			Width: 5, Height: 7,
			Data: [][]bool{
				{true, true, false, false, true},
				{true, true, false, true, false},
				{false, false, false, true, false},
				{false, false, true, false, false},
				{false, true, false, false, false},
				{false, true, false, true, true},
				{true, false, false, true, true},
			},
		},
	},
	Icons: nil,
}
