package glyphs

// Font5x7 is a complete 5×7 pixel monospace font
// Extracted and expanded from internal/widget/error.go
var Font5x7 = &GlyphSet{
	Name:        "5x7",
	GlyphWidth:  5,
	GlyphHeight: 7,
	Glyphs: map[rune]*Glyph{
		// Uppercase letters A-Z
		'A': {
			Width: 5, Height: 7,
			Data: [][]bool{
				{false, true, true, true, false},
				{true, false, false, false, true},
				{true, false, false, false, true},
				{true, true, true, true, true},
				{true, false, false, false, true},
				{true, false, false, false, true},
				{true, false, false, false, true},
			},
		},
		'B': {
			Width: 5, Height: 7,
			Data: [][]bool{
				{true, true, true, true, false},
				{true, false, false, false, true},
				{true, false, false, false, true},
				{true, true, true, true, false},
				{true, false, false, false, true},
				{true, false, false, false, true},
				{true, true, true, true, false},
			},
		},
		'C': {
			Width: 5, Height: 7,
			Data: [][]bool{
				{false, true, true, true, false},
				{true, false, false, false, true},
				{true, false, false, false, false},
				{true, false, false, false, false},
				{true, false, false, false, false},
				{true, false, false, false, true},
				{false, true, true, true, false},
			},
		},
		'D': {
			Width: 5, Height: 7,
			Data: [][]bool{
				{true, true, true, true, false},
				{true, false, false, false, true},
				{true, false, false, false, true},
				{true, false, false, false, true},
				{true, false, false, false, true},
				{true, false, false, false, true},
				{true, true, true, true, false},
			},
		},
		'E': {
			Width: 5, Height: 7,
			Data: [][]bool{
				{true, true, true, true, true},
				{true, false, false, false, false},
				{true, false, false, false, false},
				{true, true, true, true, false},
				{true, false, false, false, false},
				{true, false, false, false, false},
				{true, true, true, true, true},
			},
		},
		'F': {
			Width: 5, Height: 7,
			Data: [][]bool{
				{true, true, true, true, true},
				{true, false, false, false, false},
				{true, false, false, false, false},
				{true, true, true, true, false},
				{true, false, false, false, false},
				{true, false, false, false, false},
				{true, false, false, false, false},
			},
		},
		'G': {
			Width: 5, Height: 7,
			Data: [][]bool{
				{false, true, true, true, false},
				{true, false, false, false, true},
				{true, false, false, false, false},
				{true, false, true, true, true},
				{true, false, false, false, true},
				{true, false, false, false, true},
				{false, true, true, true, true},
			},
		},
		'H': {
			Width: 5, Height: 7,
			Data: [][]bool{
				{true, false, false, false, true},
				{true, false, false, false, true},
				{true, false, false, false, true},
				{true, true, true, true, true},
				{true, false, false, false, true},
				{true, false, false, false, true},
				{true, false, false, false, true},
			},
		},
		'I': {
			Width: 5, Height: 7,
			Data: [][]bool{
				{false, true, true, true, false},
				{false, false, true, false, false},
				{false, false, true, false, false},
				{false, false, true, false, false},
				{false, false, true, false, false},
				{false, false, true, false, false},
				{false, true, true, true, false},
			},
		},
		'J': {
			Width: 5, Height: 7,
			Data: [][]bool{
				{false, false, false, false, true},
				{false, false, false, false, true},
				{false, false, false, false, true},
				{false, false, false, false, true},
				{false, false, false, false, true},
				{true, false, false, false, true},
				{false, true, true, true, false},
			},
		},
		'K': {
			Width: 5, Height: 7,
			Data: [][]bool{
				{true, false, false, false, true},
				{true, false, false, true, false},
				{true, false, true, false, false},
				{true, true, false, false, false},
				{true, false, true, false, false},
				{true, false, false, true, false},
				{true, false, false, false, true},
			},
		},
		'L': {
			Width: 5, Height: 7,
			Data: [][]bool{
				{true, false, false, false, false},
				{true, false, false, false, false},
				{true, false, false, false, false},
				{true, false, false, false, false},
				{true, false, false, false, false},
				{true, false, false, false, false},
				{true, true, true, true, true},
			},
		},
		'M': {
			Width: 5, Height: 7,
			Data: [][]bool{
				{true, false, false, false, true},
				{true, true, false, true, true},
				{true, false, true, false, true},
				{true, false, false, false, true},
				{true, false, false, false, true},
				{true, false, false, false, true},
				{true, false, false, false, true},
			},
		},
		'N': {
			Width: 5, Height: 7,
			Data: [][]bool{
				{true, false, false, false, true},
				{true, true, false, false, true},
				{true, false, true, false, true},
				{true, false, false, true, true},
				{true, false, false, false, true},
				{true, false, false, false, true},
				{true, false, false, false, true},
			},
		},
		'O': {
			Width: 5, Height: 7,
			Data: [][]bool{
				{false, true, true, true, false},
				{true, false, false, false, true},
				{true, false, false, false, true},
				{true, false, false, false, true},
				{true, false, false, false, true},
				{true, false, false, false, true},
				{false, true, true, true, false},
			},
		},
		'P': {
			Width: 5, Height: 7,
			Data: [][]bool{
				{true, true, true, true, false},
				{true, false, false, false, true},
				{true, false, false, false, true},
				{true, true, true, true, false},
				{true, false, false, false, false},
				{true, false, false, false, false},
				{true, false, false, false, false},
			},
		},
		'Q': {
			Width: 5, Height: 7,
			Data: [][]bool{
				{false, true, true, true, false},
				{true, false, false, false, true},
				{true, false, false, false, true},
				{true, false, false, false, true},
				{true, false, true, false, true},
				{true, false, false, true, false},
				{false, true, true, false, true},
			},
		},
		'R': {
			Width: 5, Height: 7,
			Data: [][]bool{
				{true, true, true, true, false},
				{true, false, false, false, true},
				{true, false, false, false, true},
				{true, true, true, true, false},
				{true, false, true, false, false},
				{true, false, false, true, false},
				{true, false, false, false, true},
			},
		},
		'S': {
			Width: 5, Height: 7,
			Data: [][]bool{
				{false, true, true, true, false},
				{true, false, false, false, true},
				{true, false, false, false, false},
				{false, true, true, true, false},
				{false, false, false, false, true},
				{true, false, false, false, true},
				{false, true, true, true, false},
			},
		},
		'T': {
			Width: 5, Height: 7,
			Data: [][]bool{
				{true, true, true, true, true},
				{false, false, true, false, false},
				{false, false, true, false, false},
				{false, false, true, false, false},
				{false, false, true, false, false},
				{false, false, true, false, false},
				{false, false, true, false, false},
			},
		},
		'U': {
			Width: 5, Height: 7,
			Data: [][]bool{
				{true, false, false, false, true},
				{true, false, false, false, true},
				{true, false, false, false, true},
				{true, false, false, false, true},
				{true, false, false, false, true},
				{true, false, false, false, true},
				{false, true, true, true, false},
			},
		},
		'V': {
			Width: 5, Height: 7,
			Data: [][]bool{
				{true, false, false, false, true},
				{true, false, false, false, true},
				{true, false, false, false, true},
				{true, false, false, false, true},
				{false, true, false, true, false},
				{false, true, false, true, false},
				{false, false, true, false, false},
			},
		},
		'W': {
			Width: 5, Height: 7,
			Data: [][]bool{
				{true, false, false, false, true},
				{true, false, false, false, true},
				{true, false, false, false, true},
				{true, false, true, false, true},
				{true, false, true, false, true},
				{true, true, false, true, true},
				{true, false, false, false, true},
			},
		},
		'X': {
			Width: 5, Height: 7,
			Data: [][]bool{
				{true, false, false, false, true},
				{true, false, false, false, true},
				{false, true, false, true, false},
				{false, false, true, false, false},
				{false, true, false, true, false},
				{true, false, false, false, true},
				{true, false, false, false, true},
			},
		},
		'Y': {
			Width: 5, Height: 7,
			Data: [][]bool{
				{true, false, false, false, true},
				{true, false, false, false, true},
				{false, true, false, true, false},
				{false, false, true, false, false},
				{false, false, true, false, false},
				{false, false, true, false, false},
				{false, false, true, false, false},
			},
		},
		'Z': {
			Width: 5, Height: 7,
			Data: [][]bool{
				{true, true, true, true, true},
				{false, false, false, false, true},
				{false, false, false, true, false},
				{false, false, true, false, false},
				{false, true, false, false, false},
				{true, false, false, false, false},
				{true, true, true, true, true},
			},
		},

		// Digits 0-9
		'0': {
			Width: 5, Height: 7,
			Data: [][]bool{
				{false, true, true, true, false},
				{true, false, false, false, true},
				{true, false, false, true, true},
				{true, false, true, false, true},
				{true, true, false, false, true},
				{true, false, false, false, true},
				{false, true, true, true, false},
			},
		},
		'1': {
			Width: 5, Height: 7,
			Data: [][]bool{
				{false, false, true, false, false},
				{false, true, true, false, false},
				{false, false, true, false, false},
				{false, false, true, false, false},
				{false, false, true, false, false},
				{false, false, true, false, false},
				{false, true, true, true, false},
			},
		},
		'2': {
			Width: 5, Height: 7,
			Data: [][]bool{
				{false, true, true, true, false},
				{true, false, false, false, true},
				{false, false, false, false, true},
				{false, false, false, true, false},
				{false, false, true, false, false},
				{false, true, false, false, false},
				{true, true, true, true, true},
			},
		},
		'3': {
			Width: 5, Height: 7,
			Data: [][]bool{
				{false, true, true, true, false},
				{true, false, false, false, true},
				{false, false, false, false, true},
				{false, false, true, true, false},
				{false, false, false, false, true},
				{true, false, false, false, true},
				{false, true, true, true, false},
			},
		},
		'4': {
			Width: 5, Height: 7,
			Data: [][]bool{
				{false, false, false, true, false},
				{false, false, true, true, false},
				{false, true, false, true, false},
				{true, false, false, true, false},
				{true, true, true, true, true},
				{false, false, false, true, false},
				{false, false, false, true, false},
			},
		},
		'5': {
			Width: 5, Height: 7,
			Data: [][]bool{
				{true, true, true, true, true},
				{true, false, false, false, false},
				{true, true, true, true, false},
				{false, false, false, false, true},
				{false, false, false, false, true},
				{true, false, false, false, true},
				{false, true, true, true, false},
			},
		},
		'6': {
			Width: 5, Height: 7,
			Data: [][]bool{
				{false, false, true, true, false},
				{false, true, false, false, false},
				{true, false, false, false, false},
				{true, true, true, true, false},
				{true, false, false, false, true},
				{true, false, false, false, true},
				{false, true, true, true, false},
			},
		},
		'7': {
			Width: 5, Height: 7,
			Data: [][]bool{
				{true, true, true, true, true},
				{false, false, false, false, true},
				{false, false, false, true, false},
				{false, false, true, false, false},
				{false, true, false, false, false},
				{false, true, false, false, false},
				{false, true, false, false, false},
			},
		},
		'8': {
			Width: 5, Height: 7,
			Data: [][]bool{
				{false, true, true, true, false},
				{true, false, false, false, true},
				{true, false, false, false, true},
				{false, true, true, true, false},
				{true, false, false, false, true},
				{true, false, false, false, true},
				{false, true, true, true, false},
			},
		},
		'9': {
			Width: 5, Height: 7,
			Data: [][]bool{
				{false, true, true, true, false},
				{true, false, false, false, true},
				{true, false, false, false, true},
				{false, true, true, true, true},
				{false, false, false, false, true},
				{false, false, false, true, false},
				{false, true, true, false, false},
			},
		},

		// Basic punctuation and symbols
		' ': {
			Width: 5, Height: 7,
			Data: [][]bool{
				{false, false, false, false, false},
				{false, false, false, false, false},
				{false, false, false, false, false},
				{false, false, false, false, false},
				{false, false, false, false, false},
				{false, false, false, false, false},
				{false, false, false, false, false},
			},
		},
		'!': {
			Width: 5, Height: 7,
			Data: [][]bool{
				{false, false, true, false, false},
				{false, false, true, false, false},
				{false, false, true, false, false},
				{false, false, true, false, false},
				{false, false, true, false, false},
				{false, false, false, false, false},
				{false, false, true, false, false},
			},
		},
		'.': {
			Width: 5, Height: 7,
			Data: [][]bool{
				{false, false, false, false, false},
				{false, false, false, false, false},
				{false, false, false, false, false},
				{false, false, false, false, false},
				{false, false, false, false, false},
				{false, false, false, false, false},
				{false, false, true, false, false},
			},
		},
		',': {
			Width: 5, Height: 7,
			Data: [][]bool{
				{false, false, false, false, false},
				{false, false, false, false, false},
				{false, false, false, false, false},
				{false, false, false, false, false},
				{false, false, false, false, false},
				{false, false, true, false, false},
				{false, true, false, false, false},
			},
		},
		':': {
			Width: 5, Height: 7,
			Data: [][]bool{
				{false, false, false, false, false},
				{false, false, false, false, false},
				{false, false, true, false, false},
				{false, false, false, false, false},
				{false, false, false, false, false},
				{false, false, true, false, false},
				{false, false, false, false, false},
			},
		},
		';': {
			Width: 5, Height: 7,
			Data: [][]bool{
				{false, false, false, false, false},
				{false, false, false, false, false},
				{false, false, true, false, false},
				{false, false, false, false, false},
				{false, false, false, false, false},
				{false, false, true, false, false},
				{false, true, false, false, false},
			},
		},
		'?': {
			Width: 5, Height: 7,
			Data: [][]bool{
				{false, true, true, true, false},
				{true, false, false, false, true},
				{false, false, false, false, true},
				{false, false, false, true, false},
				{false, false, true, false, false},
				{false, false, false, false, false},
				{false, false, true, false, false},
			},
		},
		'-': {
			Width: 5, Height: 7,
			Data: [][]bool{
				{false, false, false, false, false},
				{false, false, false, false, false},
				{false, false, false, false, false},
				{true, true, true, true, true},
				{false, false, false, false, false},
				{false, false, false, false, false},
				{false, false, false, false, false},
			},
		},
		'/': {
			Width: 5, Height: 7,
			Data: [][]bool{
				{false, false, false, false, true},
				{false, false, false, true, false},
				{false, false, false, true, false},
				{false, false, true, false, false},
				{false, true, false, false, false},
				{false, true, false, false, false},
				{true, false, false, false, false},
			},
		},
		'(': {
			Width: 5, Height: 7,
			Data: [][]bool{
				{false, false, true, false, false},
				{false, true, false, false, false},
				{false, true, false, false, false},
				{false, true, false, false, false},
				{false, true, false, false, false},
				{false, true, false, false, false},
				{false, false, true, false, false},
			},
		},
		')': {
			Width: 5, Height: 7,
			Data: [][]bool{
				{false, false, true, false, false},
				{false, false, false, true, false},
				{false, false, false, true, false},
				{false, false, false, true, false},
				{false, false, false, true, false},
				{false, false, false, true, false},
				{false, false, true, false, false},
			},
		},
		'%': {
			Width: 5, Height: 7,
			Data: [][]bool{
				{true, true, false, false, true},
				{true, true, false, true, false},
				{false, false, false, true, false},
				{false, false, true, false, false},
				{false, true, false, false, false},
				{false, true, false, true, true},
				{true, false, false, true, true},
			},
		},

		// Lowercase letters a-z (traditional typography)
		// X-height letters use rows 2-6, ascenders use rows 0-6, descenders use rows 1-6
		'a': { // x-height
			Width: 5, Height: 7,
			Data: [][]bool{
				{false, false, false, false, false},
				{false, false, false, false, false},
				{false, true, true, true, false},
				{false, false, false, false, true},
				{false, true, true, true, true},
				{true, false, false, false, true},
				{false, true, true, true, true},
			},
		},
		'b': { // ascender - full height
			Width: 5, Height: 7,
			Data: [][]bool{
				{true, false, false, false, false},
				{true, false, false, false, false},
				{true, true, true, true, false},
				{true, false, false, false, true},
				{true, false, false, false, true},
				{true, false, false, false, true},
				{true, true, true, true, false},
			},
		},
		'c': { // x-height
			Width: 5, Height: 7,
			Data: [][]bool{
				{false, false, false, false, false},
				{false, false, false, false, false},
				{false, true, true, true, false},
				{true, false, false, false, true},
				{true, false, false, false, false},
				{true, false, false, false, true},
				{false, true, true, true, false},
			},
		},
		'd': { // ascender - full height
			Width: 5, Height: 7,
			Data: [][]bool{
				{false, false, false, false, true},
				{false, false, false, false, true},
				{false, true, true, true, true},
				{true, false, false, false, true},
				{true, false, false, false, true},
				{true, false, false, false, true},
				{false, true, true, true, true},
			},
		},
		'e': { // x-height
			Width: 5, Height: 7,
			Data: [][]bool{
				{false, false, false, false, false},
				{false, false, false, false, false},
				{false, true, true, true, false},
				{true, false, false, false, true},
				{true, true, true, true, true},
				{true, false, false, false, false},
				{false, true, true, true, false},
			},
		},
		'f': { // ascender - full height
			Width: 5, Height: 7,
			Data: [][]bool{
				{false, false, true, true, false},
				{false, true, false, false, true},
				{false, true, false, false, false},
				{true, true, true, true, false},
				{false, true, false, false, false},
				{false, true, false, false, false},
				{false, true, false, false, false},
			},
		},
		'g': { // descender - rows 1-6
			Width: 5, Height: 7,
			Data: [][]bool{
				{false, false, false, false, false},
				{false, true, true, true, true},
				{true, false, false, false, true},
				{true, false, false, false, true},
				{false, true, true, true, true},
				{false, false, false, false, true},
				{false, true, true, true, false},
			},
		},
		'h': { // ascender - full height
			Width: 5, Height: 7,
			Data: [][]bool{
				{true, false, false, false, false},
				{true, false, false, false, false},
				{true, true, true, true, false},
				{true, false, false, false, true},
				{true, false, false, false, true},
				{true, false, false, false, true},
				{true, false, false, false, true},
			},
		},
		'i': { // dot above - special case, rows 0 + 2-6
			Width: 5, Height: 7,
			Data: [][]bool{
				{false, false, true, false, false},
				{false, false, false, false, false},
				{false, true, true, false, false},
				{false, false, true, false, false},
				{false, false, true, false, false},
				{false, false, true, false, false},
				{false, true, true, true, false},
			},
		},
		'j': { // dot above + descender - special case
			Width: 5, Height: 7,
			Data: [][]bool{
				{false, false, false, true, false},
				{false, false, false, false, false},
				{false, false, true, true, false},
				{false, false, false, true, false},
				{false, false, false, true, false},
				{true, false, false, true, false},
				{false, true, true, false, false},
			},
		},
		'k': { // ascender - full height
			Width: 5, Height: 7,
			Data: [][]bool{
				{true, false, false, false, false},
				{true, false, false, false, false},
				{true, false, false, true, false},
				{true, false, true, false, false},
				{true, true, false, false, false},
				{true, false, true, false, false},
				{true, false, false, true, false},
			},
		},
		'l': { // ascender - full height
			Width: 5, Height: 7,
			Data: [][]bool{
				{false, true, true, false, false},
				{false, false, true, false, false},
				{false, false, true, false, false},
				{false, false, true, false, false},
				{false, false, true, false, false},
				{false, false, true, false, false},
				{false, true, true, true, false},
			},
		},
		'm': { // x-height
			Width: 5, Height: 7,
			Data: [][]bool{
				{false, false, false, false, false},
				{false, false, false, false, false},
				{true, true, false, true, false},
				{true, false, true, false, true},
				{true, false, true, false, true},
				{true, false, true, false, true},
				{true, false, false, false, true},
			},
		},
		'n': { // x-height
			Width: 5, Height: 7,
			Data: [][]bool{
				{false, false, false, false, false},
				{false, false, false, false, false},
				{true, true, true, true, false},
				{true, false, false, false, true},
				{true, false, false, false, true},
				{true, false, false, false, true},
				{true, false, false, false, true},
			},
		},
		'o': { // x-height
			Width: 5, Height: 7,
			Data: [][]bool{
				{false, false, false, false, false},
				{false, false, false, false, false},
				{false, true, true, true, false},
				{true, false, false, false, true},
				{true, false, false, false, true},
				{true, false, false, false, true},
				{false, true, true, true, false},
			},
		},
		'p': { // descender - rows 1-6
			Width: 5, Height: 7,
			Data: [][]bool{
				{false, false, false, false, false},
				{true, true, true, true, false},
				{true, false, false, false, true},
				{true, false, false, false, true},
				{true, true, true, true, false},
				{true, false, false, false, false},
				{true, false, false, false, false},
			},
		},
		'q': { // descender - rows 1-6
			Width: 5, Height: 7,
			Data: [][]bool{
				{false, false, false, false, false},
				{false, true, true, true, true},
				{true, false, false, false, true},
				{true, false, false, false, true},
				{false, true, true, true, true},
				{false, false, false, false, true},
				{false, false, false, false, true},
			},
		},
		'r': { // x-height
			Width: 5, Height: 7,
			Data: [][]bool{
				{false, false, false, false, false},
				{false, false, false, false, false},
				{true, false, true, true, false},
				{true, true, false, false, true},
				{true, false, false, false, false},
				{true, false, false, false, false},
				{true, false, false, false, false},
			},
		},
		's': { // x-height
			Width: 5, Height: 7,
			Data: [][]bool{
				{false, false, false, false, false},
				{false, false, false, false, false},
				{false, true, true, true, true},
				{true, false, false, false, false},
				{false, true, true, true, false},
				{false, false, false, false, true},
				{true, true, true, true, false},
			},
		},
		't': { // ascender - full height
			Width: 5, Height: 7,
			Data: [][]bool{
				{false, true, false, false, false},
				{false, true, false, false, false},
				{true, true, true, true, false},
				{false, true, false, false, false},
				{false, true, false, false, false},
				{false, true, false, false, true},
				{false, false, true, true, false},
			},
		},
		'u': { // x-height
			Width: 5, Height: 7,
			Data: [][]bool{
				{false, false, false, false, false},
				{false, false, false, false, false},
				{true, false, false, false, true},
				{true, false, false, false, true},
				{true, false, false, false, true},
				{true, false, false, false, true},
				{false, true, true, true, true},
			},
		},
		'v': { // x-height
			Width: 5, Height: 7,
			Data: [][]bool{
				{false, false, false, false, false},
				{false, false, false, false, false},
				{true, false, false, false, true},
				{true, false, false, false, true},
				{true, false, false, false, true},
				{false, true, false, true, false},
				{false, false, true, false, false},
			},
		},
		'w': { // x-height
			Width: 5, Height: 7,
			Data: [][]bool{
				{false, false, false, false, false},
				{false, false, false, false, false},
				{true, false, false, false, true},
				{true, false, true, false, true},
				{true, false, true, false, true},
				{true, false, true, false, true},
				{false, true, false, true, false},
			},
		},
		'x': { // x-height
			Width: 5, Height: 7,
			Data: [][]bool{
				{false, false, false, false, false},
				{false, false, false, false, false},
				{true, false, false, false, true},
				{false, true, false, true, false},
				{false, false, true, false, false},
				{false, true, false, true, false},
				{true, false, false, false, true},
			},
		},
		'y': { // descender - rows 1-6
			Width: 5, Height: 7,
			Data: [][]bool{
				{false, false, false, false, false},
				{true, false, false, false, true},
				{true, false, false, false, true},
				{true, false, false, false, true},
				{false, true, true, true, true},
				{false, false, false, false, true},
				{false, true, true, true, false},
			},
		},
		'z': { // x-height
			Width: 5, Height: 7,
			Data: [][]bool{
				{false, false, false, false, false},
				{false, false, false, false, false},
				{true, true, true, true, true},
				{false, false, false, true, false},
				{false, false, true, false, false},
				{false, true, false, false, false},
				{true, true, true, true, true},
			},
		},
	},
	Icons: nil,
}
