package glyphs

// KeyboardIcons8x8 contains 8×8 pixel keyboard indicator icons
var KeyboardIcons8x8 = &GlyphSet{
	Name:        "keyboard_8x8",
	GlyphWidth:  8,
	GlyphHeight: 8,
	Glyphs:      nil,
	Icons: map[string]*Glyph{
		"arrow_up": {
			Width: 8, Height: 8,
			Data: [][]bool{
				{false, false, false, true, true, false, false, false},
				{false, false, true, true, true, true, false, false},
				{false, true, true, true, true, true, true, false},
				{true, true, true, true, true, true, true, true},
				{false, false, false, true, true, false, false, false},
				{false, false, false, true, true, false, false, false},
				{false, false, false, true, true, false, false, false},
				{false, false, false, false, false, false, false, false},
			},
		},
		"arrow_down": {
			Width: 8, Height: 8,
			Data: [][]bool{
				{false, false, false, false, false, false, false, false},
				{false, false, false, true, true, false, false, false},
				{false, false, false, true, true, false, false, false},
				{false, false, false, true, true, false, false, false},
				{true, true, true, true, true, true, true, true},
				{false, true, true, true, true, true, true, false},
				{false, false, true, true, true, true, false, false},
				{false, false, false, true, true, false, false, false},
			},
		},
		"lock_closed": {
			Width: 8, Height: 8,
			Data: [][]bool{
				{false, false, true, true, true, true, false, false},
				{false, true, false, false, false, false, true, false},
				{false, true, false, false, false, false, true, false},
				{true, true, true, true, true, true, true, true},
				{true, true, true, true, true, true, true, true},
				{true, true, true, false, false, true, true, true},
				{true, true, true, true, true, true, true, true},
				{true, true, true, true, true, true, true, true},
			},
		},
		"lock_open": {
			Width: 8, Height: 8,
			Data: [][]bool{
				{false, false, true, true, true, true, false, false},
				{false, true, false, false, false, false, true, false},
				{false, true, false, false, false, false, false, false},
				{true, true, true, true, true, true, true, true},
				{true, true, true, true, true, true, true, true},
				{true, true, true, false, false, true, true, true},
				{true, true, true, true, true, true, true, true},
				{true, true, true, true, true, true, true, true},
			},
		},
	},
}

// KeyboardIcons12x12 contains 12×12 pixel keyboard indicator icons
var KeyboardIcons12x12 = &GlyphSet{
	Name:        "keyboard_12x12",
	GlyphWidth:  12,
	GlyphHeight: 12,
	Glyphs:      nil,
	Icons: map[string]*Glyph{
		"arrow_up": {
			Width: 12, Height: 12,
			Data: [][]bool{
				{false, false, false, false, false, true, true, false, false, false, false, false},
				{false, false, false, false, true, true, true, true, false, false, false, false},
				{false, false, false, true, true, true, true, true, true, false, false, false},
				{false, false, true, true, true, true, true, true, true, true, false, false},
				{false, true, true, true, true, true, true, true, true, true, true, false},
				{true, true, true, true, true, true, true, true, true, true, true, true},
				{false, false, false, false, true, true, true, true, false, false, false, false},
				{false, false, false, false, true, true, true, true, false, false, false, false},
				{false, false, false, false, true, true, true, true, false, false, false, false},
				{false, false, false, false, true, true, true, true, false, false, false, false},
				{false, false, false, false, true, true, true, true, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, false},
			},
		},
		"arrow_down": {
			Width: 12, Height: 12,
			Data: [][]bool{
				{false, false, false, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, true, true, true, true, false, false, false, false},
				{false, false, false, false, true, true, true, true, false, false, false, false},
				{false, false, false, false, true, true, true, true, false, false, false, false},
				{false, false, false, false, true, true, true, true, false, false, false, false},
				{false, false, false, false, true, true, true, true, false, false, false, false},
				{true, true, true, true, true, true, true, true, true, true, true, true},
				{false, true, true, true, true, true, true, true, true, true, true, false},
				{false, false, true, true, true, true, true, true, true, true, false, false},
				{false, false, false, true, true, true, true, true, true, false, false, false},
				{false, false, false, false, true, true, true, true, false, false, false, false},
				{false, false, false, false, false, true, true, false, false, false, false, false},
			},
		},
		"lock_closed": {
			Width: 12, Height: 12,
			Data: [][]bool{
				{false, false, false, true, true, true, true, true, true, false, false, false},
				{false, false, true, true, false, false, false, false, true, true, false, false},
				{false, true, true, false, false, false, false, false, false, true, true, false},
				{false, true, true, false, false, false, false, false, false, true, true, false},
				{true, true, true, true, true, true, true, true, true, true, true, true},
				{true, true, true, true, true, true, true, true, true, true, true, true},
				{true, true, true, true, true, true, true, true, true, true, true, true},
				{true, true, true, true, false, false, false, false, true, true, true, true},
				{true, true, true, true, false, false, false, false, true, true, true, true},
				{true, true, true, true, true, true, true, true, true, true, true, true},
				{true, true, true, true, true, true, true, true, true, true, true, true},
				{true, true, true, true, true, true, true, true, true, true, true, true},
			},
		},
		"lock_open": {
			Width: 12, Height: 12,
			Data: [][]bool{
				{false, false, false, true, true, true, true, true, true, false, false, false},
				{false, false, true, true, false, false, false, false, true, true, false, false},
				{false, true, true, false, false, false, false, false, false, false, false, false},
				{false, true, true, false, false, false, false, false, false, false, false, false},
				{true, true, true, true, true, true, true, true, true, true, true, true},
				{true, true, true, true, true, true, true, true, true, true, true, true},
				{true, true, true, true, true, true, true, true, true, true, true, true},
				{true, true, true, true, false, false, false, false, true, true, true, true},
				{true, true, true, true, false, false, false, false, true, true, true, true},
				{true, true, true, true, true, true, true, true, true, true, true, true},
				{true, true, true, true, true, true, true, true, true, true, true, true},
				{true, true, true, true, true, true, true, true, true, true, true, true},
			},
		},
	},
}

// KeyboardIcons16x16 contains 16×16 pixel keyboard indicator icons
var KeyboardIcons16x16 = &GlyphSet{
	Name:        "keyboard_16x16",
	GlyphWidth:  16,
	GlyphHeight: 16,
	Glyphs:      nil,
	Icons: map[string]*Glyph{
		"arrow_up": {
			Width: 16, Height: 16,
			Data: [][]bool{
				{false, false, false, false, false, false, false, true, true, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, true, true, true, true, false, false, false, false, false, false},
				{false, false, false, false, false, true, true, true, true, true, true, false, false, false, false, false},
				{false, false, false, false, true, true, true, true, true, true, true, true, false, false, false, false},
				{false, false, false, true, true, true, true, true, true, true, true, true, true, false, false, false},
				{false, false, true, true, true, true, true, true, true, true, true, true, true, true, false, false},
				{false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false},
				{true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true},
				{false, false, false, false, false, false, true, true, true, true, false, false, false, false, false, false},
				{false, false, false, false, false, false, true, true, true, true, false, false, false, false, false, false},
				{false, false, false, false, false, false, true, true, true, true, false, false, false, false, false, false},
				{false, false, false, false, false, false, true, true, true, true, false, false, false, false, false, false},
				{false, false, false, false, false, false, true, true, true, true, false, false, false, false, false, false},
				{false, false, false, false, false, false, true, true, true, true, false, false, false, false, false, false},
				{false, false, false, false, false, false, true, true, true, true, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
			},
		},
		"arrow_down": {
			Width: 16, Height: 16,
			Data: [][]bool{
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, true, true, true, true, false, false, false, false, false, false},
				{false, false, false, false, false, false, true, true, true, true, false, false, false, false, false, false},
				{false, false, false, false, false, false, true, true, true, true, false, false, false, false, false, false},
				{false, false, false, false, false, false, true, true, true, true, false, false, false, false, false, false},
				{false, false, false, false, false, false, true, true, true, true, false, false, false, false, false, false},
				{false, false, false, false, false, false, true, true, true, true, false, false, false, false, false, false},
				{false, false, false, false, false, false, true, true, true, true, false, false, false, false, false, false},
				{true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true},
				{false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false},
				{false, false, true, true, true, true, true, true, true, true, true, true, true, true, false, false},
				{false, false, false, true, true, true, true, true, true, true, true, true, true, false, false, false},
				{false, false, false, false, true, true, true, true, true, true, true, true, false, false, false, false},
				{false, false, false, false, false, true, true, true, true, true, true, false, false, false, false, false},
				{false, false, false, false, false, false, true, true, true, true, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, true, true, false, false, false, false, false, false, false},
			},
		},
		"lock_closed": {
			Width: 16, Height: 16,
			Data: [][]bool{
				{false, false, false, false, true, true, true, true, true, true, true, true, false, false, false, false},
				{false, false, false, true, true, true, false, false, false, false, true, true, true, false, false, false},
				{false, false, true, true, true, false, false, false, false, false, false, true, true, true, false, false},
				{false, false, true, true, false, false, false, false, false, false, false, false, true, true, false, false},
				{false, true, true, true, false, false, false, false, false, false, false, false, true, true, true, false},
				{false, true, true, true, false, false, false, false, false, false, false, false, true, true, true, false},
				{true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true},
				{true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true},
				{true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true},
				{true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true},
				{true, true, true, true, true, true, false, false, false, false, true, true, true, true, true, true},
				{true, true, true, true, true, true, false, false, false, false, true, true, true, true, true, true},
				{true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true},
				{true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true},
				{true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true},
				{true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true},
			},
		},
		"lock_open": {
			Width: 16, Height: 16,
			Data: [][]bool{
				{false, false, false, false, true, true, true, true, true, true, true, true, false, false, false, false},
				{false, false, false, true, true, true, false, false, false, false, true, true, true, false, false, false},
				{false, false, true, true, true, false, false, false, false, false, false, false, false, false, false, false},
				{false, false, true, true, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, true, true, true, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, true, true, true, false, false, false, false, false, false, false, false, false, false, false, false},
				{true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true},
				{true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true},
				{true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true},
				{true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true},
				{true, true, true, true, true, true, false, false, false, false, true, true, true, true, true, true},
				{true, true, true, true, true, true, false, false, false, false, true, true, true, true, true, true},
				{true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true},
				{true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true},
				{true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true},
				{true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true},
			},
		},
	},
}
