package glyphs

// WeatherIcons16x16 contains weather condition icons optimized for 16x16 display
var WeatherIcons16x16 = &GlyphSet{
	Name:        "weather_16x16",
	GlyphWidth:  16,
	GlyphHeight: 16,
	Glyphs:      nil,
	Icons: map[string]*Glyph{
		// Sun - clear sky (circle with rays)
		"sun": {
			Width: 16, Height: 16,
			Data: [][]bool{
				{false, false, false, false, false, false, false, true, true, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, true, true, false, false, false, false, false, false, false},
				{false, false, false, true, false, false, false, false, false, false, false, false, true, false, false, false},
				{false, false, false, false, true, false, false, false, false, false, false, true, false, false, false, false},
				{false, false, false, false, false, false, true, true, true, true, false, false, false, false, false, false},
				{false, false, false, false, false, true, true, true, true, true, true, false, false, false, false, false},
				{false, false, false, false, true, true, true, true, true, true, true, true, false, false, false, false},
				{true, true, false, false, true, true, true, true, true, true, true, true, false, false, true, true},
				{true, true, false, false, true, true, true, true, true, true, true, true, false, false, true, true},
				{false, false, false, false, true, true, true, true, true, true, true, true, false, false, false, false},
				{false, false, false, false, false, true, true, true, true, true, true, false, false, false, false, false},
				{false, false, false, false, false, false, true, true, true, true, false, false, false, false, false, false},
				{false, false, false, false, true, false, false, false, false, false, false, true, false, false, false, false},
				{false, false, false, true, false, false, false, false, false, false, false, false, true, false, false, false},
				{false, false, false, false, false, false, false, true, true, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, true, true, false, false, false, false, false, false, false},
			},
		},
		// Cloud - overcast
		"cloud": {
			Width: 16, Height: 16,
			Data: [][]bool{
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, true, true, true, true, false, false, false, false, false, false, false},
				{false, false, false, false, true, true, true, true, true, true, false, false, false, false, false, false},
				{false, false, false, true, true, true, true, true, true, true, true, false, false, false, false, false},
				{false, false, true, true, true, true, true, true, true, true, true, true, true, false, false, false},
				{false, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false},
				{false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false},
				{true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true},
				{true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true},
				{false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
			},
		},
		// Partly cloudy - sun behind cloud
		"partly_cloudy": {
			Width: 16, Height: 16,
			Data: [][]bool{
				{false, false, false, false, false, false, false, false, false, true, true, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, true, true, false, false, false, false, false},
				{false, false, false, false, false, false, false, true, false, false, false, false, true, false, false, false},
				{false, false, false, false, false, false, false, false, true, true, true, true, false, false, false, false},
				{false, false, false, false, false, true, true, true, true, true, true, true, true, false, false, false},
				{false, false, false, false, true, true, true, true, true, true, true, true, true, true, true, false},
				{false, false, false, true, true, true, true, true, true, true, true, true, false, false, true, true},
				{false, false, true, true, true, true, true, true, true, true, true, true, false, false, false, false},
				{false, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false},
				{true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false},
				{true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true},
				{false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
			},
		},
		// Rain - cloud with raindrops
		"rain": {
			Width: 16, Height: 16,
			Data: [][]bool{
				{false, false, false, false, false, true, true, true, true, false, false, false, false, false, false, false},
				{false, false, false, false, true, true, true, true, true, true, false, false, false, false, false, false},
				{false, false, false, true, true, true, true, true, true, true, true, false, false, false, false, false},
				{false, false, true, true, true, true, true, true, true, true, true, true, true, false, false, false},
				{false, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false},
				{false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false},
				{true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true},
				{true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true},
				{false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, false},
				{false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, false},
				{false, true, false, false, false, true, false, false, false, true, false, false, false, true, false, false},
				{false, true, false, false, false, true, false, false, false, true, false, false, false, true, false, false},
				{true, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
			},
		},
		// Snow - cloud with snowflakes
		"snow": {
			Width: 16, Height: 16,
			Data: [][]bool{
				{false, false, false, false, false, true, true, true, true, false, false, false, false, false, false, false},
				{false, false, false, false, true, true, true, true, true, true, false, false, false, false, false, false},
				{false, false, false, true, true, true, true, true, true, true, true, false, false, false, false, false},
				{false, false, true, true, true, true, true, true, true, true, true, true, true, false, false, false},
				{false, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false},
				{false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false},
				{true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true},
				{true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true},
				{false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, false, true, false, false, false, false, true, false, false, false, false, true, false, false, false},
				{false, true, true, true, false, false, true, true, true, false, false, true, true, true, false, false},
				{false, false, true, false, false, false, false, true, false, false, false, false, true, false, false, false},
				{false, false, false, false, true, false, false, false, false, true, false, false, false, false, true, false},
				{false, false, false, true, true, true, false, false, true, true, true, false, false, true, true, true},
				{false, false, false, false, true, false, false, false, false, true, false, false, false, false, true, false},
			},
		},
		// Storm - cloud with lightning bolt
		"storm": {
			Width: 16, Height: 16,
			Data: [][]bool{
				{false, false, false, false, false, true, true, true, true, false, false, false, false, false, false, false},
				{false, false, false, false, true, true, true, true, true, true, false, false, false, false, false, false},
				{false, false, false, true, true, true, true, true, true, true, true, false, false, false, false, false},
				{false, false, true, true, true, true, true, true, true, true, true, true, true, false, false, false},
				{false, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false},
				{false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false},
				{true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true},
				{true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true},
				{false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false},
				{false, false, false, false, false, false, false, true, true, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, true, true, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, true, true, true, true, true, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, true, true, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, true, true, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, true, true, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, true, false, false, false, false, false, false, false, false, false, false},
			},
		},
		// Fog/mist - horizontal lines
		"fog": {
			Width: 16, Height: 16,
			Data: [][]bool{
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, false, true, true, true, true, true, true, true, true, true, true, true, true, false, false},
				{false, false, true, true, true, true, true, true, true, true, true, true, true, true, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false},
				{false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true},
				{true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false},
				{false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
			},
		},
		// Drizzle - cloud with light rain
		"drizzle": {
			Width: 16, Height: 16,
			Data: [][]bool{
				{false, false, false, false, false, true, true, true, true, false, false, false, false, false, false, false},
				{false, false, false, false, true, true, true, true, true, true, false, false, false, false, false, false},
				{false, false, false, true, true, true, true, true, true, true, true, false, false, false, false, false},
				{false, false, true, true, true, true, true, true, true, true, true, true, true, false, false, false},
				{false, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false},
				{false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false},
				{true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true},
				{true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true},
				{false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, false, false, true, false, false, false, false, true, false, false, false, false, true, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, true, false, false, false, false, true, false, false, false, false, true, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, true, false, false, false, false, true, false, false, false, false, true, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
			},
		},
		// AQI Good - checkmark in circle
		"aqi_good": {
			Width: 16, Height: 16,
			Data: [][]bool{
				{false, false, false, false, false, true, true, true, true, true, true, false, false, false, false, false},
				{false, false, false, true, true, true, true, true, true, true, true, true, true, false, false, false},
				{false, false, true, true, true, true, true, true, true, true, true, true, true, true, false, false},
				{false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false},
				{false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false},
				{true, true, true, true, true, true, true, true, true, true, true, true, false, true, true, true},
				{true, true, true, true, true, true, true, true, true, true, true, false, false, true, true, true},
				{true, true, true, true, true, true, true, true, true, true, false, false, true, true, true, true},
				{true, true, false, false, true, true, true, true, true, false, false, true, true, true, true, true},
				{true, true, true, false, false, true, true, true, false, false, true, true, true, true, true, true},
				{true, true, true, true, false, false, true, false, false, true, true, true, true, true, true, true},
				{false, true, true, true, true, false, false, false, true, true, true, true, true, true, true, false},
				{false, true, true, true, true, true, false, true, true, true, true, true, true, true, true, false},
				{false, false, true, true, true, true, true, true, true, true, true, true, true, true, false, false},
				{false, false, false, true, true, true, true, true, true, true, true, true, true, false, false, false},
				{false, false, false, false, false, true, true, true, true, true, true, false, false, false, false, false},
			},
		},
		// AQI Moderate - warning triangle
		"aqi_moderate": {
			Width: 16, Height: 16,
			Data: [][]bool{
				{false, false, false, false, false, false, false, true, true, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, true, true, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, true, true, true, true, false, false, false, false, false, false},
				{false, false, false, false, false, false, true, true, true, true, false, false, false, false, false, false},
				{false, false, false, false, false, true, true, true, true, true, true, false, false, false, false, false},
				{false, false, false, false, false, true, true, false, false, true, true, false, false, false, false, false},
				{false, false, false, false, true, true, true, false, false, true, true, true, false, false, false, false},
				{false, false, false, false, true, true, true, false, false, true, true, true, false, false, false, false},
				{false, false, false, true, true, true, true, false, false, true, true, true, true, false, false, false},
				{false, false, false, true, true, true, true, false, false, true, true, true, true, false, false, false},
				{false, false, true, true, true, true, true, true, true, true, true, true, true, true, false, false},
				{false, false, true, true, true, true, true, false, false, true, true, true, true, true, false, false},
				{false, true, true, true, true, true, true, false, false, true, true, true, true, true, true, false},
				{false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false},
				{true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true},
				{true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true},
			},
		},
		// AQI Bad - X in circle
		"aqi_bad": {
			Width: 16, Height: 16,
			Data: [][]bool{
				{false, false, false, false, false, true, true, true, true, true, true, false, false, false, false, false},
				{false, false, false, true, true, true, true, true, true, true, true, true, true, false, false, false},
				{false, false, true, true, true, true, true, true, true, true, true, true, true, true, false, false},
				{false, true, true, false, false, true, true, true, true, true, true, false, false, true, true, false},
				{false, true, true, true, false, false, true, true, true, true, false, false, true, true, true, false},
				{true, true, true, true, true, false, false, true, true, false, false, true, true, true, true, true},
				{true, true, true, true, true, true, false, false, false, false, true, true, true, true, true, true},
				{true, true, true, true, true, true, true, false, false, true, true, true, true, true, true, true},
				{true, true, true, true, true, true, true, false, false, true, true, true, true, true, true, true},
				{true, true, true, true, true, true, false, false, false, false, true, true, true, true, true, true},
				{true, true, true, true, true, false, false, true, true, false, false, true, true, true, true, true},
				{false, true, true, true, false, false, true, true, true, true, false, false, true, true, true, false},
				{false, true, true, false, false, true, true, true, true, true, true, false, false, true, true, false},
				{false, false, true, true, true, true, true, true, true, true, true, true, true, true, false, false},
				{false, false, false, true, true, true, true, true, true, true, true, true, true, false, false, false},
				{false, false, false, false, false, true, true, true, true, true, true, false, false, false, false, false},
			},
		},
		// AQI Unknown - question mark
		"aqi_unknown": {
			Width: 16, Height: 16,
			Data: [][]bool{
				{false, false, false, false, false, true, true, true, true, true, true, false, false, false, false, false},
				{false, false, false, true, true, true, true, true, true, true, true, true, true, false, false, false},
				{false, false, true, true, true, true, true, true, true, true, true, true, true, true, false, false},
				{false, true, true, true, true, false, false, false, false, false, true, true, true, true, true, false},
				{false, true, true, true, true, false, false, false, false, false, true, true, true, true, true, false},
				{true, true, true, true, true, true, true, true, true, false, false, true, true, true, true, true},
				{true, true, true, true, true, true, true, true, false, false, true, true, true, true, true, true},
				{true, true, true, true, true, true, true, false, false, true, true, true, true, true, true, true},
				{true, true, true, true, true, true, true, false, false, true, true, true, true, true, true, true},
				{true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true},
				{true, true, true, true, true, true, true, false, false, true, true, true, true, true, true, true},
				{false, true, true, true, true, true, true, false, false, true, true, true, true, true, true, false},
				{false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false},
				{false, false, true, true, true, true, true, false, false, true, true, true, true, true, false, false},
				{false, false, false, true, true, true, true, false, false, true, true, true, true, false, false, false},
				{false, false, false, false, false, true, true, true, true, true, true, false, false, false, false, false},
			},
		},
		// UV Low - small sun outline
		"uv_low": {
			Width: 16, Height: 16,
			Data: [][]bool{
				{false, false, false, false, false, false, false, true, true, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, true, true, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, true, true, true, true, false, false, false, false, false, false},
				{false, false, false, false, false, true, true, false, false, true, true, false, false, false, false, false},
				{false, false, false, false, true, true, false, false, false, false, true, true, false, false, false, false},
				{true, true, false, false, true, false, false, false, false, false, false, true, false, false, true, true},
				{true, true, false, false, true, false, false, false, false, false, false, true, false, false, true, true},
				{false, false, false, false, true, true, false, false, false, false, true, true, false, false, false, false},
				{false, false, false, false, false, true, true, false, false, true, true, false, false, false, false, false},
				{false, false, false, false, false, false, true, true, true, true, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, true, true, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, true, true, false, false, false, false, false, false, false},
			},
		},
		// UV Moderate - half-filled sun
		"uv_moderate": {
			Width: 16, Height: 16,
			Data: [][]bool{
				{false, false, false, false, false, false, false, true, true, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, true, true, false, false, false, false, false, false, false},
				{false, false, false, true, false, false, false, false, false, false, false, false, true, false, false, false},
				{false, false, false, false, true, false, false, false, false, false, false, true, false, false, false, false},
				{false, false, false, false, false, false, true, true, true, true, false, false, false, false, false, false},
				{false, false, false, false, false, true, true, true, true, true, true, false, false, false, false, false},
				{false, false, false, false, true, true, true, true, true, true, true, true, false, false, false, false},
				{true, true, false, false, true, true, true, true, false, false, true, true, false, false, true, true},
				{true, true, false, false, true, true, true, true, false, false, true, true, false, false, true, true},
				{false, false, false, false, true, true, true, true, true, true, true, true, false, false, false, false},
				{false, false, false, false, false, true, true, true, true, true, true, false, false, false, false, false},
				{false, false, false, false, false, false, true, true, true, true, false, false, false, false, false, false},
				{false, false, false, false, true, false, false, false, false, false, false, true, false, false, false, false},
				{false, false, false, true, false, false, false, false, false, false, false, false, true, false, false, false},
				{false, false, false, false, false, false, false, true, true, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, true, true, false, false, false, false, false, false, false},
			},
		},
		// UV High - filled sun with extra rays
		"uv_high": {
			Width: 16, Height: 16,
			Data: [][]bool{
				{false, false, false, false, false, false, false, true, true, false, false, false, false, false, false, false},
				{false, false, true, false, false, false, false, true, true, false, false, false, false, true, false, false},
				{false, false, false, true, false, false, false, false, false, false, false, false, true, false, false, false},
				{false, false, false, false, true, false, false, false, false, false, false, true, false, false, false, false},
				{false, false, false, false, false, false, true, true, true, true, false, false, false, false, false, false},
				{false, false, false, false, false, true, true, true, true, true, true, false, false, false, false, false},
				{false, false, false, false, true, true, true, true, true, true, true, true, false, false, false, false},
				{true, true, false, false, true, true, true, true, true, true, true, true, false, false, true, true},
				{true, true, false, false, true, true, true, true, true, true, true, true, false, false, true, true},
				{false, false, false, false, true, true, true, true, true, true, true, true, false, false, false, false},
				{false, false, false, false, false, true, true, true, true, true, true, false, false, false, false, false},
				{false, false, false, false, false, false, true, true, true, true, false, false, false, false, false, false},
				{false, false, false, false, true, false, false, false, false, false, false, true, false, false, false, false},
				{false, false, false, true, false, false, false, false, false, false, false, false, true, false, false, false},
				{false, false, true, false, false, false, false, true, true, false, false, false, false, true, false, false},
				{false, false, false, false, false, false, false, true, true, false, false, false, false, false, false, false},
			},
		},
		// UV Unknown - sun with question mark
		"uv_unknown": {
			Width: 16, Height: 16,
			Data: [][]bool{
				{false, false, false, false, false, false, false, true, true, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, true, true, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, true, true, true, true, false, false, false, false, false, false},
				{false, false, false, false, false, true, true, false, false, true, true, false, false, false, false, false},
				{false, false, false, false, true, true, false, false, false, true, true, true, false, false, false, false},
				{true, true, false, false, true, false, false, false, true, true, false, true, false, false, true, true},
				{true, true, false, false, true, false, false, true, true, false, false, true, false, false, true, true},
				{false, false, false, false, true, true, false, false, false, false, true, true, false, false, false, false},
				{false, false, false, false, false, true, true, true, false, true, true, false, false, false, false, false},
				{false, false, false, false, false, false, true, true, true, true, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, true, true, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, true, true, false, false, false, false, false, false, false},
			},
		},
		// Humidity Low - empty water drop
		"humidity_low": {
			Width: 16, Height: 16,
			Data: [][]bool{
				{false, false, false, false, false, false, false, true, true, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, true, true, true, true, false, false, false, false, false, false},
				{false, false, false, false, false, true, true, false, false, true, true, false, false, false, false, false},
				{false, false, false, false, true, true, false, false, false, false, true, true, false, false, false, false},
				{false, false, false, true, true, false, false, false, false, false, false, true, true, false, false, false},
				{false, false, true, true, false, false, false, false, false, false, false, false, true, true, false, false},
				{false, true, true, false, false, false, false, false, false, false, false, false, false, true, true, false},
				{false, true, true, false, false, false, false, false, false, false, false, false, false, true, true, false},
				{true, true, false, false, false, false, false, false, false, false, false, false, false, false, true, true},
				{true, true, false, false, false, false, false, false, false, false, false, false, false, false, true, true},
				{true, true, false, false, false, false, false, false, false, false, false, false, false, false, true, true},
				{true, true, false, false, false, false, false, false, false, false, false, false, false, false, true, true},
				{false, true, true, false, false, false, false, false, false, false, false, false, false, true, true, false},
				{false, false, true, true, true, false, false, false, false, false, false, true, true, true, false, false},
				{false, false, false, true, true, true, true, true, true, true, true, true, true, false, false, false},
				{false, false, false, false, false, true, true, true, true, true, true, false, false, false, false, false},
			},
		},
		// Humidity Moderate - half-filled water drop
		"humidity_moderate": {
			Width: 16, Height: 16,
			Data: [][]bool{
				{false, false, false, false, false, false, false, true, true, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, true, true, true, true, false, false, false, false, false, false},
				{false, false, false, false, false, true, true, false, false, true, true, false, false, false, false, false},
				{false, false, false, false, true, true, false, false, false, false, true, true, false, false, false, false},
				{false, false, false, true, true, false, false, false, false, false, false, true, true, false, false, false},
				{false, false, true, true, false, false, false, false, false, false, false, false, true, true, false, false},
				{false, true, true, false, false, false, false, false, false, false, false, false, false, true, true, false},
				{false, true, true, false, false, false, false, false, false, false, false, false, false, true, true, false},
				{true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true},
				{true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true},
				{true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true},
				{true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true},
				{false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false},
				{false, false, true, true, true, true, true, true, true, true, true, true, true, true, false, false},
				{false, false, false, true, true, true, true, true, true, true, true, true, true, false, false, false},
				{false, false, false, false, false, true, true, true, true, true, true, false, false, false, false, false},
			},
		},
		// Humidity High - filled water drop
		"humidity_high": {
			Width: 16, Height: 16,
			Data: [][]bool{
				{false, false, false, false, false, false, false, true, true, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, true, true, true, true, false, false, false, false, false, false},
				{false, false, false, false, false, true, true, true, true, true, true, false, false, false, false, false},
				{false, false, false, false, true, true, true, true, true, true, true, true, false, false, false, false},
				{false, false, false, true, true, true, true, true, true, true, true, true, true, false, false, false},
				{false, false, true, true, true, true, true, true, true, true, true, true, true, true, false, false},
				{false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false},
				{false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false},
				{true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true},
				{true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true},
				{true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true},
				{true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true},
				{false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false},
				{false, false, true, true, true, true, true, true, true, true, true, true, true, true, false, false},
				{false, false, false, true, true, true, true, true, true, true, true, true, true, false, false, false},
				{false, false, false, false, false, true, true, true, true, true, true, false, false, false, false, false},
			},
		},
		// Wind Calm - horizontal lines (still air)
		"wind_calm": {
			Width: 16, Height: 16,
			Data: [][]bool{
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, true, true, true, true, true, true, true, true, true, true, true, false, false, false, false},
				{false, true, true, true, true, true, true, true, true, true, true, true, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, true, true, true, true, true, true, true, true, false, false, false, false, false, false, false},
				{false, true, true, true, true, true, true, true, true, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
			},
		},
		// Wind Light - wavy line
		"wind_light": {
			Width: 16, Height: 16,
			Data: [][]bool{
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, true, true, true, false, false},
				{false, false, false, false, false, false, false, false, false, false, true, true, false, true, true, false},
				{false, true, true, true, true, true, true, true, true, true, true, false, false, false, true, false},
				{false, true, true, true, true, true, true, true, true, true, true, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, true, true, true, true, true, true, true, true, false, false, false, false, false, false, false},
				{false, true, true, true, true, true, true, true, true, true, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, true, true, true, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
			},
		},
		// Wind Moderate - multiple wavy lines
		"wind_moderate": {
			Width: 16, Height: 16,
			Data: [][]bool{
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, true, true, true, false, false},
				{false, false, false, false, false, false, false, false, false, false, true, true, false, true, true, false},
				{false, true, true, true, true, true, true, true, true, true, true, false, false, false, true, false},
				{false, true, true, true, true, true, true, true, true, true, true, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, true, true, false, false, false},
				{false, true, true, true, true, true, true, true, true, true, true, true, true, false, false, false},
				{false, true, true, true, true, true, true, true, true, true, true, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, true, true, true, true, true, true, true, true, false, false, false, false, false, false, false},
				{false, true, true, true, true, true, true, true, true, true, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, true, true, true, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
			},
		},
		// Wind Strong - multiple wavy lines with arrow
		"wind_strong": {
			Width: 16, Height: 16,
			Data: [][]bool{
				{false, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, true, true, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, true, true, true, true, false},
				{false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true},
				{false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true},
				{false, false, false, false, false, false, false, false, false, false, false, true, true, true, true, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, true, true, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, true, true, true, true, true, true, true, true, true, true, true, true, false, false, false},
				{false, true, true, true, true, true, true, true, true, true, true, true, true, false, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, true, true, true, true, true, true, true, true, true, false, false, false, false, false, false},
				{false, true, true, true, true, true, true, true, true, true, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
			},
		},
		// Wind direction arrows - Arrow pointing North (up)
		"arrow_n": {
			Width: 16, Height: 16,
			Data: [][]bool{
				{false, false, false, false, false, false, false, true, true, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, true, true, true, true, false, false, false, false, false, false},
				{false, false, false, false, false, true, true, true, true, true, true, false, false, false, false, false},
				{false, false, false, false, true, true, true, true, true, true, true, true, false, false, false, false},
				{false, false, false, true, true, true, false, true, true, false, true, true, true, false, false, false},
				{false, false, true, true, true, false, false, true, true, false, false, true, true, true, false, false},
				{false, true, true, true, false, false, false, true, true, false, false, false, true, true, true, false},
				{false, false, false, false, false, false, false, true, true, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, true, true, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, true, true, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, true, true, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, true, true, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, true, true, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, true, true, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, true, true, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
			},
		},
		// Arrow pointing South (down)
		"arrow_s": {
			Width: 16, Height: 16,
			Data: [][]bool{
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, true, true, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, true, true, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, true, true, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, true, true, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, true, true, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, true, true, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, true, true, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, true, true, false, false, false, false, false, false, false},
				{false, true, true, true, false, false, false, true, true, false, false, false, true, true, true, false},
				{false, false, true, true, true, false, false, true, true, false, false, true, true, true, false, false},
				{false, false, false, true, true, true, false, true, true, false, true, true, true, false, false, false},
				{false, false, false, false, true, true, true, true, true, true, true, true, false, false, false, false},
				{false, false, false, false, false, true, true, true, true, true, true, false, false, false, false, false},
				{false, false, false, false, false, false, true, true, true, true, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, true, true, false, false, false, false, false, false, false},
			},
		},
		// Arrow pointing East (right)
		"arrow_e": {
			Width: 16, Height: 16,
			Data: [][]bool{
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, true, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, true, true, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, true, true, true, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, true, true, true, true, false, false, false},
				{false, false, false, false, false, false, false, false, false, true, true, true, true, true, false, false},
				{false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false},
				{false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true},
				{false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true},
				{false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false},
				{false, false, false, false, false, false, false, false, false, true, true, true, true, true, false, false},
				{false, false, false, false, false, false, false, false, false, true, true, true, true, false, false, false},
				{false, false, false, false, false, false, false, false, false, true, true, true, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, true, true, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, true, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
			},
		},
		// Arrow pointing West (left)
		"arrow_w": {
			Width: 16, Height: 16,
			Data: [][]bool{
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, true, true, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, true, true, true, false, false, false, false, false, false, false, false, false},
				{false, false, false, true, true, true, true, false, false, false, false, false, false, false, false, false},
				{false, false, true, true, true, true, true, false, false, false, false, false, false, false, false, false},
				{false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false},
				{true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false},
				{true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false},
				{false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false},
				{false, false, true, true, true, true, true, false, false, false, false, false, false, false, false, false},
				{false, false, false, true, true, true, true, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, true, true, true, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, true, true, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
			},
		},
		// Arrow pointing NE (up-right)
		"arrow_ne": {
			Width: 16, Height: 16,
			Data: [][]bool{
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, true, true, true, true, true, true, true, true, true, true, false},
				{false, false, false, false, false, false, true, true, true, true, true, true, true, true, true, false},
				{false, false, false, false, false, false, false, true, true, true, true, true, true, true, true, false},
				{false, false, false, false, false, false, false, false, true, true, true, true, true, true, true, false},
				{false, false, false, false, false, false, false, true, true, true, true, true, true, true, false, false},
				{false, false, false, false, false, false, true, true, true, false, true, true, true, false, false, false},
				{false, false, false, false, false, true, true, true, false, false, false, true, true, false, false, false},
				{false, false, false, false, true, true, true, false, false, false, false, false, false, false, false, false},
				{false, false, false, true, true, true, false, false, false, false, false, false, false, false, false, false},
				{false, false, true, true, true, false, false, false, false, false, false, false, false, false, false, false},
				{false, true, true, true, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, true, true, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
			},
		},
		// Arrow pointing SE (down-right)
		"arrow_se": {
			Width: 16, Height: 16,
			Data: [][]bool{
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, true, true, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, true, true, true, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, false, true, true, true, false, false, false, false, false, false, false, false, false, false, false},
				{false, false, false, true, true, true, false, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, true, true, true, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, true, true, true, false, false, false, true, true, false, false, false},
				{false, false, false, false, false, false, true, true, true, false, true, true, true, false, false, false},
				{false, false, false, false, false, false, false, true, true, true, true, true, true, true, false, false},
				{false, false, false, false, false, false, false, false, true, true, true, true, true, true, true, false},
				{false, false, false, false, false, false, false, true, true, true, true, true, true, true, true, false},
				{false, false, false, false, false, false, true, true, true, true, true, true, true, true, true, false},
				{false, false, false, false, false, true, true, true, true, true, true, true, true, true, true, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
			},
		},
		// Arrow pointing SW (down-left)
		"arrow_sw": {
			Width: 16, Height: 16,
			Data: [][]bool{
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, true, true, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, true, true, true, false},
				{false, false, false, false, false, false, false, false, false, false, false, true, true, true, false, false},
				{false, false, false, false, false, false, false, false, false, false, true, true, true, false, false, false},
				{false, false, false, false, false, false, false, false, false, true, true, true, false, false, false, false},
				{false, false, false, true, true, false, false, false, true, true, true, false, false, false, false, false},
				{false, false, false, true, true, true, false, true, true, true, false, false, false, false, false, false},
				{false, false, true, true, true, true, true, true, true, false, false, false, false, false, false, false},
				{false, true, true, true, true, true, true, true, false, false, false, false, false, false, false, false},
				{false, true, true, true, true, true, true, true, true, false, false, false, false, false, false, false},
				{false, true, true, true, true, true, true, true, true, true, false, false, false, false, false, false},
				{false, true, true, true, true, true, true, true, true, true, true, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
			},
		},
		// Arrow pointing NW (up-left)
		"arrow_nw": {
			Width: 16, Height: 16,
			Data: [][]bool{
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, true, true, true, true, true, true, true, true, true, true, false, false, false, false, false},
				{false, true, true, true, true, true, true, true, true, true, false, false, false, false, false, false},
				{false, true, true, true, true, true, true, true, true, false, false, false, false, false, false, false},
				{false, true, true, true, true, true, true, true, false, false, false, false, false, false, false, false},
				{false, false, true, true, true, true, true, true, true, false, false, false, false, false, false, false},
				{false, false, false, true, true, true, false, true, true, true, false, false, false, false, false, false},
				{false, false, false, true, true, false, false, false, true, true, true, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, true, true, true, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, false, true, true, true, false, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, true, true, true, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, true, true, true, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, true, true, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
			},
		},
	},
}

// WeatherIcons24x24 contains larger weather condition icons
var WeatherIcons24x24 = &GlyphSet{
	Name:        "weather_24x24",
	GlyphWidth:  24,
	GlyphHeight: 24,
	Glyphs:      nil,
	Icons: map[string]*Glyph{
		// Sun - clear sky (larger version)
		"sun": {
			Width: 24, Height: 24,
			Data: [][]bool{
				{false, false, false, false, false, false, false, false, false, false, false, true, true, false, false, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, true, true, false, false, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, true, false, false, false, false, false, false, true, true, false, false, false, false, false, false, true, false, false, false, false},
				{false, false, false, false, false, true, false, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, false, false},
				{false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false, false, true, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, true, true, true, true, true, true, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, true, true, true, true, true, true, true, true, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, true, true, true, true, true, true, true, true, true, true, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, true, true, true, true, true, true, true, true, true, true, true, true, false, false, false, false, false, false},
				{false, false, false, false, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false, false, false, false},
				{false, false, false, false, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false, false, false, false},
				{true, true, true, false, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false, true, true, true},
				{true, true, true, false, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false, true, true, true},
				{false, false, false, false, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false, false, false, false},
				{false, false, false, false, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false, false, false, false},
				{false, false, false, false, false, false, true, true, true, true, true, true, true, true, true, true, true, true, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, true, true, true, true, true, true, true, true, true, true, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, true, true, true, true, true, true, true, true, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, true, true, true, true, true, true, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false, false, true, false, false, false, false, false, false},
				{false, false, false, false, false, true, false, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, false, false},
				{false, false, false, false, true, false, false, false, false, false, false, true, true, false, false, false, false, false, false, true, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, true, true, false, false, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, true, true, false, false, false, false, false, false, false, false, false, false, false},
			},
		},
		// Cloud - overcast (larger version)
		"cloud": {
			Width: 24, Height: 24,
			Data: [][]bool{
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, true, true, true, true, true, true, false, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, true, true, true, true, true, true, true, true, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, true, true, true, true, true, true, true, true, true, true, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, true, true, true, true, true, true, true, true, true, true, true, true, false, false, false, false, false, false, false},
				{false, false, false, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false, false, false, false},
				{false, false, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false, false, false},
				{false, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false, false},
				{false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false},
				{false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false},
				{true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true},
				{true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true},
				{true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true},
				{false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false},
				{false, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
			},
		},
	},
}
