package glyphs

// WeatherIcons16x16 contains weather condition icons optimized for 16x16 display
var WeatherIcons16x16 = &GlyphSet{
	Name:        "weather_16x16",
	GlyphWidth:  16,
	GlyphHeight: 16,
	Glyphs:      nil,
	Icons: map[string]*Glyph{
		// Sun - clear sky (circle with rays)
		"sun": {
			Width: 16, Height: 16,
			Data: [][]bool{
				{false, false, false, false, false, false, false, true, true, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, true, true, false, false, false, false, false, false, false},
				{false, false, false, true, false, false, false, false, false, false, false, false, true, false, false, false},
				{false, false, false, false, true, false, false, false, false, false, false, true, false, false, false, false},
				{false, false, false, false, false, false, true, true, true, true, false, false, false, false, false, false},
				{false, false, false, false, false, true, true, true, true, true, true, false, false, false, false, false},
				{false, false, false, false, true, true, true, true, true, true, true, true, false, false, false, false},
				{true, true, false, false, true, true, true, true, true, true, true, true, false, false, true, true},
				{true, true, false, false, true, true, true, true, true, true, true, true, false, false, true, true},
				{false, false, false, false, true, true, true, true, true, true, true, true, false, false, false, false},
				{false, false, false, false, false, true, true, true, true, true, true, false, false, false, false, false},
				{false, false, false, false, false, false, true, true, true, true, false, false, false, false, false, false},
				{false, false, false, false, true, false, false, false, false, false, false, true, false, false, false, false},
				{false, false, false, true, false, false, false, false, false, false, false, false, true, false, false, false},
				{false, false, false, false, false, false, false, true, true, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, true, true, false, false, false, false, false, false, false},
			},
		},
		// Cloud - overcast
		"cloud": {
			Width: 16, Height: 16,
			Data: [][]bool{
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, true, true, true, true, false, false, false, false, false, false, false},
				{false, false, false, false, true, true, true, true, true, true, false, false, false, false, false, false},
				{false, false, false, true, true, true, true, true, true, true, true, false, false, false, false, false},
				{false, false, true, true, true, true, true, true, true, true, true, true, true, false, false, false},
				{false, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false},
				{false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false},
				{true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true},
				{true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true},
				{false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
			},
		},
		// Partly cloudy - sun behind cloud
		"partly_cloudy": {
			Width: 16, Height: 16,
			Data: [][]bool{
				{false, false, false, false, false, false, false, false, false, true, true, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, true, true, false, false, false, false, false},
				{false, false, false, false, false, false, false, true, false, false, false, false, true, false, false, false},
				{false, false, false, false, false, false, false, false, true, true, true, true, false, false, false, false},
				{false, false, false, false, false, true, true, true, true, true, true, true, true, false, false, false},
				{false, false, false, false, true, true, true, true, true, true, true, true, true, true, true, false},
				{false, false, false, true, true, true, true, true, true, true, true, true, false, false, true, true},
				{false, false, true, true, true, true, true, true, true, true, true, true, false, false, false, false},
				{false, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false},
				{true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false},
				{true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true},
				{false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
			},
		},
		// Rain - cloud with raindrops
		"rain": {
			Width: 16, Height: 16,
			Data: [][]bool{
				{false, false, false, false, false, true, true, true, true, false, false, false, false, false, false, false},
				{false, false, false, false, true, true, true, true, true, true, false, false, false, false, false, false},
				{false, false, false, true, true, true, true, true, true, true, true, false, false, false, false, false},
				{false, false, true, true, true, true, true, true, true, true, true, true, true, false, false, false},
				{false, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false},
				{false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false},
				{true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true},
				{true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true},
				{false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, false},
				{false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, false},
				{false, true, false, false, false, true, false, false, false, true, false, false, false, true, false, false},
				{false, true, false, false, false, true, false, false, false, true, false, false, false, true, false, false},
				{true, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
			},
		},
		// Snow - cloud with snowflakes
		"snow": {
			Width: 16, Height: 16,
			Data: [][]bool{
				{false, false, false, false, false, true, true, true, true, false, false, false, false, false, false, false},
				{false, false, false, false, true, true, true, true, true, true, false, false, false, false, false, false},
				{false, false, false, true, true, true, true, true, true, true, true, false, false, false, false, false},
				{false, false, true, true, true, true, true, true, true, true, true, true, true, false, false, false},
				{false, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false},
				{false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false},
				{true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true},
				{true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true},
				{false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, false, true, false, false, false, false, true, false, false, false, false, true, false, false, false},
				{false, true, true, true, false, false, true, true, true, false, false, true, true, true, false, false},
				{false, false, true, false, false, false, false, true, false, false, false, false, true, false, false, false},
				{false, false, false, false, true, false, false, false, false, true, false, false, false, false, true, false},
				{false, false, false, true, true, true, false, false, true, true, true, false, false, true, true, true},
				{false, false, false, false, true, false, false, false, false, true, false, false, false, false, true, false},
			},
		},
		// Storm - cloud with lightning bolt
		"storm": {
			Width: 16, Height: 16,
			Data: [][]bool{
				{false, false, false, false, false, true, true, true, true, false, false, false, false, false, false, false},
				{false, false, false, false, true, true, true, true, true, true, false, false, false, false, false, false},
				{false, false, false, true, true, true, true, true, true, true, true, false, false, false, false, false},
				{false, false, true, true, true, true, true, true, true, true, true, true, true, false, false, false},
				{false, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false},
				{false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false},
				{true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true},
				{true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true},
				{false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false},
				{false, false, false, false, false, false, false, true, true, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, true, true, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, true, true, true, true, true, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, true, true, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, true, true, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, true, true, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, true, false, false, false, false, false, false, false, false, false, false},
			},
		},
		// Fog/mist - horizontal lines
		"fog": {
			Width: 16, Height: 16,
			Data: [][]bool{
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, false, true, true, true, true, true, true, true, true, true, true, true, true, false, false},
				{false, false, true, true, true, true, true, true, true, true, true, true, true, true, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false},
				{false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true},
				{true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false},
				{false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
			},
		},
		// Drizzle - cloud with light rain
		"drizzle": {
			Width: 16, Height: 16,
			Data: [][]bool{
				{false, false, false, false, false, true, true, true, true, false, false, false, false, false, false, false},
				{false, false, false, false, true, true, true, true, true, true, false, false, false, false, false, false},
				{false, false, false, true, true, true, true, true, true, true, true, false, false, false, false, false},
				{false, false, true, true, true, true, true, true, true, true, true, true, true, false, false, false},
				{false, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false},
				{false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false},
				{true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true},
				{true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true},
				{false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, false, false, true, false, false, false, false, true, false, false, false, false, true, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, true, false, false, false, false, true, false, false, false, false, true, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, true, false, false, false, false, true, false, false, false, false, true, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
			},
		},
	},
}

// WeatherIcons24x24 contains larger weather condition icons
var WeatherIcons24x24 = &GlyphSet{
	Name:        "weather_24x24",
	GlyphWidth:  24,
	GlyphHeight: 24,
	Glyphs:      nil,
	Icons: map[string]*Glyph{
		// Sun - clear sky (larger version)
		"sun": {
			Width: 24, Height: 24,
			Data: [][]bool{
				{false, false, false, false, false, false, false, false, false, false, false, true, true, false, false, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, true, true, false, false, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, true, false, false, false, false, false, false, true, true, false, false, false, false, false, false, true, false, false, false, false},
				{false, false, false, false, false, true, false, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, false, false},
				{false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false, false, true, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, true, true, true, true, true, true, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, true, true, true, true, true, true, true, true, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, true, true, true, true, true, true, true, true, true, true, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, true, true, true, true, true, true, true, true, true, true, true, true, false, false, false, false, false, false},
				{false, false, false, false, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false, false, false, false},
				{false, false, false, false, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false, false, false, false},
				{true, true, true, false, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false, true, true, true},
				{true, true, true, false, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false, true, true, true},
				{false, false, false, false, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false, false, false, false},
				{false, false, false, false, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false, false, false, false},
				{false, false, false, false, false, false, true, true, true, true, true, true, true, true, true, true, true, true, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, true, true, true, true, true, true, true, true, true, true, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, true, true, true, true, true, true, true, true, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, true, true, true, true, true, true, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false, false, true, false, false, false, false, false, false},
				{false, false, false, false, false, true, false, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, false, false},
				{false, false, false, false, true, false, false, false, false, false, false, true, true, false, false, false, false, false, false, true, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, true, true, false, false, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, true, true, false, false, false, false, false, false, false, false, false, false, false},
			},
		},
		// Cloud - overcast (larger version)
		"cloud": {
			Width: 24, Height: 24,
			Data: [][]bool{
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, true, true, true, true, true, true, false, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, true, true, true, true, true, true, true, true, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, true, true, true, true, true, true, true, true, true, true, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, true, true, true, true, true, true, true, true, true, true, true, true, false, false, false, false, false, false, false},
				{false, false, false, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false, false, false, false},
				{false, false, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false, false, false},
				{false, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false, false},
				{false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false},
				{false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false},
				{true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true},
				{true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true},
				{true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true},
				{false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false},
				{false, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
			},
		},
	},
}
