package glyphs

// SpotifyIcons contains Spotify-related icons in multiple sizes
var SpotifyIcons = &GlyphSet{
	Name:        "spotify",
	GlyphWidth:  32,
	GlyphHeight: 32,
	Glyphs:      nil,
	Icons: map[string]*Glyph{
		// Spotify logo - 32x32
		"logo": {
			Width: 32, Height: 32,
			Data: [][]bool{
				{false, false, false, false, false, false, false, false, false, false, false, false, true, true, true, true, true, true, true, true, false, false, false, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false, false, false, false, false},
				{false, false, false, false, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false, false, false, false},
				{false, false, false, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false, false, false},
				{false, false, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false, false},
				{false, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false},
				{false, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false},
				{false, true, true, true, true, true, false, false, false, false, false, false, false, false, false, false, false, false, false, true, true, true, true, true, true, true, true, true, true, true, true, false},
				{false, true, true, true, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, true, true, true, true, true, true, true, false},
				{false, true, true, true, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, true, true, true, true, true, false},
				{true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false, false, false, false, false, false, false, false, true, true, true, true, true},
				{true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false, false, false, false, false, true, true, true, true},
				{true, true, true, true, true, true, true, true, true, true, false, false, false, false, false, true, true, true, true, true, true, true, true, true, false, false, false, false, true, true, true, true},
				{true, true, true, true, true, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, true, true, true, true, true, true, true, true, true, true, true},
				{true, true, true, true, true, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, true, true, true, true, true, true, true, true},
				{true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false, false, false, false, false, false, true, true, true, true, true, true, true},
				{true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false, false, false, false, true, true, true, true, true, true},
				{true, true, true, true, true, true, true, true, true, true, false, false, false, false, false, true, true, true, true, true, true, true, true, false, false, true, true, true, true, true, true, true},
				{false, true, true, true, true, true, true, false, false, false, false, false, false, false, false, false, false, false, false, true, true, true, true, true, true, true, true, true, true, true, true, false},
				{false, true, true, true, true, true, true, false, false, false, true, true, true, true, true, false, false, false, false, false, false, false, true, true, true, true, true, true, true, true, true, false},
				{false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false, false, false, true, true, true, true, true, true, true, true, false},
				{false, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, true, true, true, true, true, true, true, false, false},
				{false, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false},
				{false, false, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false, false},
				{false, false, false, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false, false, false},
				{false, false, false, false, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false, false, false, false},
				{false, false, false, false, false, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false, false, false, false, false, false, false, false},
				{false, false, false, false, false, false, false, false, false, false, false, false, true, true, true, true, true, true, true, true, false, false, false, false, false, false, false, false, false, false, false, false},
			},
		},
		// Spotify logo - 16x16
		"logo_16": {
			Width: 16, Height: 16,
			Data: [][]bool{
				{false, false, false, false, false, false, true, true, true, true, false, false, false, false, false, false},
				{false, false, false, true, true, true, true, true, true, true, true, true, true, false, false, false},
				{false, false, true, true, true, true, true, true, true, true, true, true, true, true, false, false},
				{false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false},
				{false, true, true, false, false, false, false, false, false, true, true, true, true, true, true, false},
				{false, true, false, false, false, false, false, false, false, false, false, false, true, true, true, false},
				{true, true, true, true, true, true, true, true, true, false, false, false, false, false, true, true},
				{true, true, true, false, false, false, false, false, false, false, true, true, false, false, true, true},
				{true, true, true, false, false, false, false, false, false, false, false, false, true, true, true, true},
				{true, true, true, true, true, false, false, true, true, true, true, false, false, true, true, true},
				{false, true, true, false, false, false, false, false, false, false, false, true, true, true, true, false},
				{false, true, true, true, true, true, true, true, true, true, false, false, true, true, true, false},
				{false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false},
				{false, false, true, true, true, true, true, true, true, true, true, true, true, true, false, false},
				{false, false, false, true, true, true, true, true, true, true, true, true, true, false, false, false},
				{false, false, false, false, false, false, true, true, true, true, false, false, false, false, false, false},
			},
		},
		// Spotify logo - 12x12
		"logo_12": {
			Width: 12, Height: 12,
			Data: [][]bool{
				{false, false, false, false, true, true, true, true, false, false, false, false},
				{false, false, true, true, true, true, true, true, true, true, false, false},
				{false, true, true, true, true, true, true, true, true, true, true, false},
				{false, true, true, false, false, false, false, true, true, true, true, false},
				{true, true, false, false, false, false, false, false, false, false, true, true},
				{true, true, true, true, false, false, true, true, true, false, true, true},
				{true, true, true, false, false, false, false, false, false, true, true, true},
				{true, true, true, true, false, false, true, true, true, false, true, true},
				{false, true, true, true, true, true, true, false, true, true, true, true},
				{false, true, true, true, true, true, true, true, true, true, true, false},
				{false, false, true, true, true, true, true, true, true, true, false, false},
				{false, false, false, false, true, true, true, true, true, false, false, false},
			},
		},
	},
}
